CC = gcc
CFLAGS = -g -Wall

ex_1_1: vetor.c ex_1_1.c vetor.h
	gcc $(CFLAGS) vetor.c ex_1_1.c vetor.h -o ex_1_1

ex_1_2: lista_cno.c ex_1_2.c lista_cno.h
	gcc $(CFLAGS) lista_cno.c ex_1_2.c lista_cno.h -o ex_1_2

ex_1_3: lista_sno.c ex_1_3.c lista_sno.h
	gcc $(CFLAGS) lista_sno.c ex_1_3.c lista_sno.h -o ex_1_3

ex_1_4: lista_circ.c ex_1_4.c lista_circ.h
	gcc $(CFLAGS) lista_circ.c ex_1_4.c lista_circ.h -o ex_1_4

ex_1_5: lista_dupla.c ex_1_5.c lista_dupla.h
	gcc $(CFLAGS) lista_dupla.c ex_1_5.c lista_dupla.h -o ex_1_5

ex_2: lista_cno.c ex_2.c lista_cno.h
	gcc $(CFLAGS) lista_cno.c ex_2.c lista_cno.h -o ex_2

ex_5: lista_sno.c ex_5.c lista_sno.h
	gcc $(CFLAGS) lista_sno.c ex_5.c lista_sno.h -o ex_5

ex_7: lista_string.c ex_7.c lista_string.h
	gcc $(CFLAGS) lista_string.c ex_7.c lista_string.h -o ex_7

ex_9: lista_sno.c ex_9.c lista_sno.h
	gcc $(CFLAGS) lista_sno.c ex_9.c lista_sno.h -o ex_9

ex_10: lista_sno.c ex_10.c lista_sno.h
	gcc $(CFLAGS) lista_sno.c ex_10.c lista_sno.h -o ex_10
